name: Documentation

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true
  

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install package and documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
      - name: Generate analysis documentation
        run: |
            python docs/generate_analysis_rst.py
      - name: Build HTML documentation
        run: |
          sphinx-build \
            -b html \
            docs/source \
            docs/build/html

      - name: Check links
        run: |
          sphinx-build \
            -b linkcheck \
            docs/source \
            docs/build/linkcheck

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/build/html


      - name: Publish documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/feature/github_actions'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build/html
          force_orphan: true  